resources:
  repositories:
    - repository: templates
      name: azdo-templates
      type: git

trigger:
  - "*"

jobs:
  - template: git-mirror.jobs.v1.yml@templates
    parameters:
      remote_url: git@github.com:gstmichel/golden-images.git
